<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/AdminMasterPage.master" AutoEventWireup="true" CodeFile="AdmintOperatingSystem.aspx.cs" Inherits="Admin_AdmintOperatingSystem" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <link href="../OnlineExaminationSystem.css" rel="stylesheet" /> 
     <link href="../Content_area-2.css" rel="stylesheet" />
    <link href="../Content_area.css" rel="stylesheet" />
    <link href="../OnlineExam.css" rel="stylesheet" />
    <script src="../jQuery/jquery-3.1.0.js"></script>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <div id="main" >
           <div id="heading" >
                <h2>Welcome To Admin Operating System</h2>
           </div>
        <div id="content" >
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
                    BackColor="White" BorderColor="#3366CC" BorderStyle="None" BorderWidth="1px" 
                    CellPadding="4" AutoGenerateDeleteButton="True" 
        AutoGenerateEditButton="True" DataKeyNames="Q_no" 
        OnRowCancelingEdit="GridView1_RowCancelingEdit" 
        OnRowDeleting="GridView1_RowDeleting" OnRowEditing="GridView1_RowEditing" 
        OnRowUpdating="GridView1_RowUpdating" 
        OnSelectedIndexChanged="GridView1_SelectedIndexChanged">
                    <Columns>
                       
                        <asp:BoundField DataField="Q_no" HeaderText="Question Number" />
                        <asp:BoundField DataField="Q_Subject" HeaderText="Subject" />
                        <asp:BoundField DataField="Q_option1" HeaderText="Option A" />
                        <asp:BoundField DataField="Q_option2" HeaderText="Option B" />
                        <asp:BoundField DataField="Q_option3" HeaderText="Option C" />
                        <asp:BoundField DataField="Q_option4" HeaderText="Option D" />
                        <asp:BoundField DataField="Q_ans" HeaderText="Answer" />
                        
                        
                    </Columns>
                    <FooterStyle BackColor="#99CCCC" ForeColor="#003399" />
                    <HeaderStyle BackColor="#003399" Font-Bold="True" ForeColor="#CCCCFF" />
                    <PagerStyle BackColor="#99CCCC" ForeColor="#003399" HorizontalAlign="Left" />
                    <RowStyle BackColor="White" ForeColor="#003399" />
                    <SelectedRowStyle BackColor="#009999" Font-Bold="True" ForeColor="#CCFF99" />
                    <SortedAscendingCellStyle BackColor="#EDF6F6" />
                    <SortedAscendingHeaderStyle BackColor="#0D4AC4" />
                    <SortedDescendingCellStyle BackColor="#D6DFDF" />
                    <SortedDescendingHeaderStyle BackColor="#002876" />
                </asp:GridView>
                </div>
                </div>
</asp:Content>

