<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/AdminMasterPage.master" AutoEventWireup="true" CodeFile="RegistrationDetails.aspx.cs" Inherits="Admin_RegistrationDetails" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
     <link href="../OnlineExaminationSystem.css" rel="stylesheet" /> 
     <link href="../Content_area-2.css" rel="stylesheet" />
    <link href="../Content_area.css" rel="stylesheet" />
    <link href="../OnlineExam.css" rel="stylesheet" />
    <script src="../jQuery/jquery-3.1.0.js"></script>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <div id="main" >
           <div id="heading" >
                <h2>Welcome To Admin Registration Details</h2>
           </div>
        <div id="content" >
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
                    BackColor="White" BorderColor="#3366CC" BorderStyle="None" BorderWidth="1px" 
                    CellPadding="4" AutoGenerateDeleteButton="True" 
        AutoGenerateEditButton="True" DataKeyNames="RollNO" 
        OnRowCancelingEdit="GridView1_RowCancelingEdit" 
        OnRowDeleting="GridView1_RowDeleting" OnRowEditing="GridView1_RowEditing" 
        OnRowUpdating="GridView1_RowUpdating" 
        OnSelectedIndexChanged="GridView1_SelectedIndexChanged">
                    <Columns>
                        <asp:BoundField DataField="RollNo" HeaderText="Roll Number" />
                        <asp:BoundField DataField="S_Name" HeaderText="Name" />
                        <asp:BoundField DataField="S_FatherName" HeaderText="Father Name" />
                        <asp:BoundField DataField="DOB" HeaderText="DOB" />
                        <asp:BoundField DataField="Gender" HeaderText="Sex" />
                        <asp:BoundField DataField="Category" HeaderText="Category" />
                        <asp:BoundField DataField="Addr" HeaderText="Address" />
                        <asp:BoundField DataField="Country" HeaderText="Country" />
                        <asp:BoundField DataField="City" HeaderText="City" />
                        <asp:BoundField DataField="PinCode" HeaderText="Pin Code" />
                        <asp:BoundField DataField="ContactNo" HeaderText="Contact No" />
                        <asp:BoundField DataField="Email" HeaderText="Email ID" />
                        <asp:BoundField DataField="Qual" HeaderText="Qualification" />
                        <asp:BoundField DataField="Nationality" HeaderText="Nationality" />
                        <asp:BoundField DataField="BoardUniv" HeaderText="Board/Univercity" />
                        <asp:BoundField DataField="YearPassing" HeaderText="Year of Passing" />
                        <asp:BoundField DataField="TransactionID" HeaderText="Transaction ID" />
                        <asp:BoundField DataField="ExamName" HeaderText="Exam Name" />
                        <asp:ImageField DataImageUrlField="pic" HeaderText="Photo">
                        </asp:ImageField>
                        <asp:ImageField DataImageUrlField="sign" HeaderText="Signature">
                        </asp:ImageField>
                        
                    </Columns>
                    <FooterStyle BackColor="#99CCCC" ForeColor="#003399" />
                    <HeaderStyle BackColor="#003399" Font-Bold="True" ForeColor="#CCCCFF" />
                    <PagerStyle BackColor="#99CCCC" ForeColor="#003399" HorizontalAlign="Left" />
                    <RowStyle BackColor="White" ForeColor="#003399" />
                    <SelectedRowStyle BackColor="#009999" Font-Bold="True" ForeColor="#CCFF99" />
                    <SortedAscendingCellStyle BackColor="#EDF6F6" />
                    <SortedAscendingHeaderStyle BackColor="#0D4AC4" />
                    <SortedDescendingCellStyle BackColor="#D6DFDF" />
                    <SortedDescendingHeaderStyle BackColor="#002876" />
                </asp:GridView>
                </div>
                </div>
</asp:Content>

