<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/AdminMasterPage.master" AutoEventWireup="true" CodeFile="ResultDetails.aspx.cs" Inherits="Admin_ResultDetails" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
     <link href="../OnlineExaminationSystem.css" rel="stylesheet" /> 
     <link href="../Content_area-2.css" rel="stylesheet" />
    <link href="../Content_area.css" rel="stylesheet" />
    <link href="../OnlineExam.css" rel="stylesheet" />
    <script src="../jQuery/jquery-3.1.0.js"></script>
     <style type="text/css">
         .auto-style6
         {
             width: 283px;
         }
     </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <div id="main" style="height:600px;" >
           <div id="heading" >
                <h2>Welcome To Admin Result Details</h2>
           </div>
        <div id="content" style="height:600px;" >
        <table>
        <tr>
        <td class="auto-style6"></td>
        <td>
     <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
                    BackColor="White" BorderColor="#3366CC" BorderStyle="None" BorderWidth="1px" 
                    CellPadding="4" AutoGenerateDeleteButton="True" 
        AutoGenerateEditButton="True" DataKeyNames="R_ID" 
        OnRowCancelingEdit="GridView1_RowCancelingEdit" 
        OnRowDeleting="GridView1_RowDeleting" OnRowEditing="GridView1_RowEditing" 
        OnRowUpdating="GridView1_RowUpdating" 
        OnSelectedIndexChanged="GridView1_SelectedIndexChanged" Height="285px" 
                Width="769px">
       <Columns>
            <asp:BoundField DataField="R_ID" HeaderText="ID" />
            <asp:BoundField DataField="R_subject" HeaderText="Subject" />
            <asp:BoundField DataField="R_marks" HeaderText="Marks" />
            <asp:BoundField DataField="R_status" HeaderText="Status" />
            <asp:BoundField DataField="R_TimeDate" HeaderText="Time Date" />
            <asp:BoundField DataField="RollNo" HeaderText="Roll Number" />
        </Columns>
        <FooterStyle BackColor="#99CCCC" ForeColor="#003399" />
        <HeaderStyle BackColor="#003399" Font-Bold="True" ForeColor="#CCCCFF" />
        <PagerStyle BackColor="#99CCCC" ForeColor="#003399" HorizontalAlign="Left" />
        <RowStyle BackColor="White" ForeColor="#003399" />
        <SelectedRowStyle BackColor="#009999" Font-Bold="True" ForeColor="#CCFF99" />
        <SortedAscendingCellStyle BackColor="#EDF6F6" />
        <SortedAscendingHeaderStyle BackColor="#0D4AC4" />
        <SortedDescendingCellStyle BackColor="#D6DFDF" />
        <SortedDescendingHeaderStyle BackColor="#002876" />
    </asp:GridView>
    </td>
    </tr></table>
    </div>
    </div>
</asp:Content>

